apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 03_was.yaml
resources:
- 03_was.yaml
images:
- name: was-image
  newName: public.ecr.aws/e1q1j6q7/was
  newTag: v1
namespace: default
