apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 01_db.yaml
resources:
- 01_db.yaml
images:
- name: db-image
  newName: public.ecr.aws/e1q1j6q7/db
  newTag: v1
namespace: default
