apiVersion: v1
kind: Service
metadata:
  name: was-svc
spec:
  selector:
    app: mywas
  ports:
  - port: 8080
    targetPort: 8080
  # type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywas
spec:
  replicas: 3
  selector:       #selector와 labels를 서비스와 일치시켜야 함
    matchLabels:
      app: mywas
  template:
    metadata:
      labels:
        app: mywas
    spec:
      containers:
      - name: mywas
        image: cicd-image
        ports:
        - containerPort: 8080
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-0.mysql-svc.default.svc.cluster.local; do echo waiting for db-0.mysql-svc; sleep 2; done"]
      - name: wait-for-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis-svc.default.svc.cluster.local; do echo waiting for redis-svc; sleep 2; done"]        