apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 03_was.yaml
resources:
- 03_was.yaml
images:
- name: cicd-image
  newName: eeunchong/rapa-cicdlab2
  newTag: v32
namespace: default
