apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- 03_was.yaml
resources:
- 03_was.yaml
images:
- name: cicd-image
  newName: eeunchong/rapa-cicdlab2
<<<<<<< HEAD
  newTag: "24"
=======
  newTag: v29
>>>>>>> f477b793da3276e214b68af3ee4341da5ce38cc6
namespace: default
