name: CICD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - run : ls -al
      
      - name: Set env # 환경 변수 세팅
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
        
      - name: chmod gradle
        run: chmod +x ./gradlew
          
      - name: build
        run: ./gradlew build --no-daemon
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
    
      - name: docker build
        run: |
          mv ./build/libs/*.war ./Dockerfile
          docker build -t ${{ secrets.ECR_URI }}/was:v${{ env.RELEASE_VERSION }} ./Dockerfile
          docker build -t ${{ secrets.ECR_URI }}/was:latest ./Dockerfile
          rm -Rf ./Dockerfile/*.war
          rm -Rf ./build  

      - name: Get ECR Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Get image
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e1q1j6q7

      - name: docker push
        run: | 
          docker push ${{ secrets.ECR_URI }}/was:v${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.ECR_URI }}/was:latest

      # - name: Update kube config
      #   run: aws eks update-kubeconfig --name frodo --region ap-northeast-2
      
      # - name: was-deploy restart
      #   run: kubectl set image deploy was was=${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:v${{ env.RELEASE_VERSION }}
      
      
      - name: Update Kubernetes resources
        run: |
          cd yaml/was
          kustomize edit set image was-image=${{ secrets.ECR_URI }}/was:v${{ env.RELEASE_VERSION }}
          cat kustomization.yml
              
      - name: Commit & Push Image 
        uses: actions-js/push@master
        with:
          message: '[was] Update Image : ${{ secrets.ECR_URI }}/was:v${{ env.RELEASE_VERSION }}'
          branch: main
          github_token: ${{ secrets.TOKEN }}
