name: CICD
on:
  push:
    branches: [ main ]
    # paths-ignore:
    # - '.github/workflows/**'    

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run : ls -al
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: chmod gradle
        run: chmod +x ./gradlew
          
      - name: build
        run: ./gradlew build --no-daemon
          
      - name: docker build
        run: |
          mv ./build/libs/*.war ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:v${{ env.RELEASE_VERSION }} ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:latest ./Dockerfile
          rm -Rf ./Dockerfile/*.war
          rm -Rf ./build  

      - name: docker images check
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: docer push
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:v${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:latest

      # - name: Get EKS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-2
      
      # - name: Update kube config
      #   run: aws eks update-kubeconfig --name test --region ap-northeast-2
      
      # - name: was-deploy restart
      #   run: kubectl set image deploy mywas mywas=${{ secrets.DOCKERHUB_USERNAME }}/rapa-cicdlab2:v${{ env.RELEASE_VERSION }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: git-cicd

      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          cd ./yaml/kustomize/
          kustomize edit set image cicd-image=jongdo737/rapa-cidc:${{ env.RELEASE_VERSION }}
          cat kustomization.yml
          
      # 수정된 파일 commit & push
      - name: Commit files
        run: |
          
          git config --global user.email 'dldmschd97@gmail.com'
          git config --global user.name 'Eeunchong'
          git add ./yaml/kustomize/kustomization.yml
          git commit -m "Update image tag to ${{ env.RELEASE_VERSION }}"
          git push